import React, { useState, useEffect } from 'react';
import {
  AlertOctagon,
  AlertTriangle,
  CheckCircle2,
  Volume2,
  VolumeX,
  PhoneCall,
  Share2,
  Check,
  RotateCcw,
  Sparkles,
  ShieldCheck,
  MapPin,
  Heart,
  ChevronRight,
} from 'lucide-react';
import { Language, TriageResult, SeverityLevel } from '../types';
import { useSpeechSynthesis } from '../hooks/useSpeechSynthesis';

interface TriageResultCardProps {
  result: TriageResult;
  language: Language;
  onReset: () => void;
  onOpenQuickDial: () => void;
  /** How this result was produced — shown as a small badge in the header. */
  source?: 'ai' | 'offline' | null;
}

export const TriageResultCard: React.FC<TriageResultCardProps> = ({
  result,
  language,
  onReset,
  onOpenQuickDial,
  source,
}) => {
  const [completedSteps, setCompletedSteps] = useState<Record<number, boolean>>({});
  const [copiedReport, setCopiedReport] = useState(false);
  const { isPlaying, currentStepIndex, playSequence, stop } = useSpeechSynthesis();

  // Toggle step check
  const handleToggleStep = (stepNumber: number) => {
    setCompletedSteps((prev) => ({
      ...prev,
      [stepNumber]: !prev[stepNumber],
    }));
  };

  const totalSteps = result.steps.length;
  const completedCount = Object.values(completedSteps).filter(Boolean).length;
  const progressPercent = Math.round((completedCount / (totalSteps || 1)) * 100);

  // Prepare voice steps
  const voiceTexts = result.steps.map((s) =>
    language === 'hi'
      ? `कदम ${s.stepNumber}: ${s.titleHi}. ${s.instructionHi}`
      : `Step ${s.stepNumber}: ${s.title}. ${s.instruction}`
  );

  const handleToggleVoice = () => {
    if (isPlaying) {
      stop();
    } else {
      playSequence(voiceTexts, language);
    }
  };

  useEffect(() => {
    return () => {
      stop();
    };
  }, [stop]);

  const getSeverityBadge = (severity: SeverityLevel) => {
    switch (severity) {
      case 'CRITICAL':
        return {
          bg: 'bg-red-950/80 border-red-600/80 text-red-300',
          icon: <AlertOctagon className="w-5 h-5 text-red-500 animate-pulse" />,
          label: language === 'hi' ? 'अति गंभीर (Critical Emergency)' : 'CRITICAL EMERGENCY',
          bannerBg: 'from-red-950/90 via-red-900/30 to-slate-900',
        };
      case 'MODERATE':
        return {
          bg: 'bg-amber-950/80 border-amber-600/80 text-amber-300',
          icon: <AlertTriangle className="w-5 h-5 text-amber-500" />,
          label: language === 'hi' ? 'मध्यम जोखिम (Urgent Care)' : 'MODERATE URGENCY',
          bannerBg: 'from-amber-950/80 via-amber-900/20 to-slate-900',
        };
      case 'LOW':
      default:
        return {
          bg: 'bg-emerald-950/80 border-emerald-600/80 text-emerald-300',
          icon: <CheckCircle2 className="w-5 h-5 text-emerald-500" />,
          label: language === 'hi' ? 'सामान्य प्राथमिक उपचार (Minor/Low Risk)' : 'LOW RISK FIRST-AID',
          bannerBg: 'from-emerald-950/80 via-emerald-900/20 to-slate-900',
        };
    }
  };

  const badgeInfo = getSeverityBadge(result.severity);

  const handleCopyReport = () => {
    const text = `🚨 RKGIT CAMPUS TRIAGE REPORT:\nSeverity: ${result.severity}\nCondition: ${result.title}\nImmediate Action: ${result.immediateAction}\nCampus Protocol: ${result.campusProtocol}\nReport generated by RKGIT Safe Companion.`;
    navigator.clipboard.writeText(text);
    setCopiedReport(true);
    setTimeout(() => setCopiedReport(false), 2000);
  };

  return (
    <div className="rounded-3xl bg-[#0a1524]/85 border-2 border-cyan-500/20 overflow-hidden space-y-0">
      {/* Header Banner */}
      <div className={`p-4 sm:p-6 bg-gradient-to-br ${badgeInfo.bannerBg} border-b-2 border-cyan-500/20`}>
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className="p-3 rounded-2xl bg-[#0a1524]/85 border-2 border-cyan-500/25">
              {badgeInfo.icon}
            </div>
            <div>
              <div className="flex items-center gap-2 flex-wrap">
                <span className={`px-3 py-1 rounded-xl text-xs font-black tracking-wide border-2 ${badgeInfo.bg}`}>
                  {badgeInfo.label}
                </span>
                {source && (
                  <span
                    className={`px-3 py-1 rounded-xl text-xs font-black tracking-wide border-2 flex items-center gap-1 ${
                      source === 'ai'
                        ? 'bg-cyan-950/60 border-cyan-500/60 text-cyan-300'
                        : 'bg-amber-950/60 border-amber-500/60 text-amber-300'
                    }`}
                    title={
                      source === 'ai'
                        ? 'Generated live by Gemini AI'
                        : 'Local offline protocol — Gemini AI was unreachable or not configured'
                    }
                  >
                    <Sparkles className="w-3 h-3" />
                    {source === 'ai'
                      ? (language === 'hi' ? 'जेमिनी एआई द्वारा जनरेट' : 'Generated by Gemini AI')
                      : (language === 'hi' ? 'ऑफ़लाइन प्रोटोकॉल' : 'Offline Protocol')}
                  </span>
                )}
                {result.callAmbulanceRecommended && (
                  <span className="px-3 py-1 rounded-xl text-xs font-black bg-red-600 border-2 border-red-400 text-white animate-bounce">
                    {language === 'hi' ? '🚑 108 एम्बुलेंस बुलाएं' : '🚑 Call 108 Ambulance'}
                  </span>
                )}
              </div>
              <h2 className="text-lg sm:text-xl font-black text-slate-100 mt-1.5 tracking-tight">
                {language === 'hi' ? result.titleHi : result.title}
              </h2>
            </div>
          </div>

          {/* Hands-Free Voice Button & Reset */}
          <div className="flex items-center gap-2 self-start sm:self-center">
            <button
              onClick={handleToggleVoice}
              className={`flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-black transition-all active:translate-x-0.5 active:translate-y-0.5 cursor-pointer border-2 ${
                isPlaying
                  ? 'bg-red-600 border-red-400 text-white animate-pulse'
                  : 'bg-slate-800 hover:bg-slate-700 text-slate-200 border-cyan-500/25'
              }`}
              title="Voice narration for hands-free first aid"
            >
              {isPlaying ? <VolumeX className="w-4 h-4" /> : <Volume2 className="w-4 h-4 text-cyan-400" />}
              <span>
                {isPlaying
                  ? (language === 'hi' ? 'आवाज़ रोकें' : 'Stop Audio')
                  : (language === 'hi' ? 'कदम सुनें' : 'Read Aloud')}
              </span>
            </button>

            <button
              onClick={onReset}
              className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white border-2 border-cyan-500/25 transition cursor-pointer"
              title="New Triage Assessment"
            >
              <RotateCcw className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Summary Description */}
        <p className="mt-3 text-xs sm:text-sm font-medium text-slate-200 leading-relaxed">
          {language === 'hi' ? result.summaryHi : result.summary}
        </p>

        {/* Immediate 10-Second Action Callout */}
        <div className="mt-4 p-4 rounded-2xl bg-[#060c16] border-2 border-red-500/60 flex items-start gap-3.5">
          <div className="w-8 h-8 rounded-xl bg-red-600/30 border-2 border-red-500/80 flex items-center justify-center text-red-400 font-black text-xs flex-shrink-0 mt-0.5">
            10s
          </div>
          <div>
            <h4 className="text-xs font-black uppercase tracking-wider text-red-400">
              {language === 'hi' ? 'तत्काल कार्रवाई (पहले 10–30 सेकंड):' : 'IMMEDIATE ACTION (FIRST 10–30 SECONDS):'}
            </h4>
            <p className="text-xs sm:text-sm font-bold text-slate-100 mt-0.5">
              {language === 'hi' ? result.immediateActionHi : result.immediateAction}
            </p>
          </div>
        </div>
      </div>

      {/* Progress & Step by Step Protocol */}
      <div className="p-4 sm:p-6 space-y-6">
        {/* Checklist Progress Bar */}
        <div>
          <div className="flex items-center justify-between text-xs font-bold text-slate-300 mb-2">
            <span className="flex items-center gap-1.5">
              <ShieldCheck className="w-4 h-4 text-emerald-400" />
              <span>{language === 'hi' ? 'प्राथमिक उपचार चरण प्रगति' : 'First-Aid Protocol Progress'}</span>
            </span>
            <span className="text-slate-100 font-extrabold">
              {completedCount} / {totalSteps} ({progressPercent}%)
            </span>
          </div>
          <div className="w-full h-3 bg-[#060c16] rounded-full overflow-hidden border-2 border-cyan-500/20">
            <div
              className="h-full bg-gradient-to-r from-cyan-500 to-emerald-500 transition-all duration-300"
              style={{ width: `${progressPercent}%` }}
            />
          </div>
        </div>

        {/* Step List */}
        <div className="space-y-3">
          <h3 className="text-sm font-black text-slate-100 tracking-wide uppercase flex items-center gap-2">
            <span>{language === 'hi' ? 'कदम-दर-कदम निर्देश (टैप करके टिक करें):' : 'Step-by-Step Instructions (Tap to Check):'}</span>
          </h3>

          <div className="space-y-3">
            {result.steps.map((step, idx) => {
              const isChecked = !!completedSteps[step.stepNumber];
              const isBeingSpoken = isPlaying && currentStepIndex === idx;

              return (
                <div
                  key={step.stepNumber}
                  onClick={() => handleToggleStep(step.stepNumber)}
                  className={`p-4 rounded-2xl border-2 transition-all cursor-pointer select-none flex items-start gap-3.5 hover:-translate-y-0.5 ${
                    isBeingSpoken
                      ? 'bg-red-950/60 border-red-500'
                      : isChecked
                      ? 'bg-emerald-950/20 border-emerald-800/80 opacity-80'
                      : 'bg-[#060c16] border-cyan-500/20 hover:border-cyan-500/25'
                  }`}
                >
                  <button
                    type="button"
                    className={`w-6 h-6 rounded-xl border-2 flex items-center justify-center flex-shrink-0 mt-0.5 transition ${
                      isChecked
                        ? 'bg-emerald-600 border-emerald-400 text-white'
                        : 'border-cyan-500/25 bg-[#0a1524]/85 text-transparent'
                    }`}
                  >
                    <Check className="w-3.5 h-3.5 stroke-[3]" />
                  </button>

                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="text-xs font-black text-slate-400">
                        {language === 'hi' ? `चरण ${step.stepNumber}` : `Step ${step.stepNumber}`}
                      </span>
                      <h4 className={`text-xs sm:text-sm font-bold ${isChecked ? 'line-through text-slate-400' : 'text-slate-100'}`}>
                        {language === 'hi' ? step.titleHi : step.title}
                      </h4>
                      {step.isCritical && (
                        <span className="px-2 py-0.5 rounded-lg text-[9px] font-black bg-red-950 text-red-400 border border-red-800">
                          CRITICAL
                        </span>
                      )}
                    </div>
                    <p className={`text-xs mt-1 leading-relaxed font-medium ${isChecked ? 'text-slate-500' : 'text-slate-300'}`}>
                      {language === 'hi' ? step.instructionHi : step.instruction}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Warnings & What NOT to do Box */}
        {(result.warnings?.length > 0 || result.warningsHi?.length > 0) && (
          <div className="p-4 rounded-2xl bg-amber-950/40 border-2 border-amber-800/80 space-y-2">
            <h4 className="text-xs font-black text-amber-400 flex items-center gap-1.5 uppercase tracking-wider">
              <AlertTriangle className="w-4 h-4" />
              <span>{language === 'hi' ? 'सावधानी — यह बिल्कुल न करें (What NOT to Do):' : 'Warnings & Contraindications (What NOT to Do):'}</span>
            </h4>
            <ul className="space-y-1.5 text-xs text-amber-200/90 pl-5 list-disc font-medium">
              {(language === 'hi' ? result.warningsHi : result.warnings).map((w, i) => (
                <li key={i}>{w}</li>
              ))}
            </ul>
          </div>
        )}

        {/* Campus Specific Guidance */}
        <div className="p-4 rounded-2xl bg-[#060c16] border-2 border-cyan-500/20 space-y-2.5">
          <div className="flex items-center gap-2 text-xs font-extrabold text-slate-100 uppercase tracking-wide">
            <MapPin className="w-4 h-4 text-cyan-400" />
            <span>{language === 'hi' ? 'आरकेजीआईटी परिसर दिशानिर्देश' : 'RKGIT Campus Protocol & Routing'}</span>
          </div>
          <p className="text-xs text-slate-300 leading-relaxed font-medium">
            {language === 'hi' ? result.campusProtocolHi : result.campusProtocol}
          </p>
          <div className="pt-2 flex flex-wrap items-center gap-2.5">
            <a
              href="tel:+919871234560"
              className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-red-600 hover:bg-red-500 text-white text-xs font-bold border-2 border-red-400 active:translate-x-0.5 active:translate-y-0.5 transition-all"
            >
              <PhoneCall className="w-3.5 h-3.5" />
              <span>{language === 'hi' ? 'कैंपस डिस्पेंसरी: 9871234560' : 'Call Dispensary: 9871234560'}</span>
            </a>
            <button
              onClick={onOpenQuickDial}
              className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-bold border-2 border-cyan-500/25 active:translate-x-0.5 active:translate-y-0.5 transition-all cursor-pointer"
            >
              <ChevronRight className="w-3.5 h-3.5 text-cyan-400" />
              <span>{language === 'hi' ? 'अन्य सुरक्षा नंबर' : 'All Campus Contacts'}</span>
            </button>
          </div>
        </div>

        {/* Vital Signs Checklist */}
        {result.vitalSignsToCheck?.length > 0 && (
          <div className="p-4 rounded-2xl bg-[#060c16] border-2 border-cyan-500/20 flex items-center justify-between flex-wrap gap-2.5">
            <div className="flex items-center gap-2">
              <Heart className="w-4 h-4 text-rose-400" />
              <span className="text-xs font-bold text-slate-200">
                {language === 'hi' ? 'लक्षणों की निगरानी रखें:' : 'Monitor Vitals:'}
              </span>
            </div>
            <div className="flex items-center gap-1.5 flex-wrap">
              {result.vitalSignsToCheck.map((sign, i) => (
                <span
                  key={i}
                  className="px-2.5 py-1 rounded-lg text-xs font-bold bg-[#0a1524]/85 text-slate-200 border-2 border-cyan-500/20"
                >
                  {sign}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Bottom Actions */}
        <div className="pt-3 flex flex-col sm:flex-row items-center justify-between gap-3 border-t-2 border-cyan-500/20">
          <button
            onClick={handleCopyReport}
            className="w-full sm:w-auto flex items-center justify-center gap-1.5 px-4 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 active:translate-x-0.5 active:translate-y-0.5 text-slate-200 text-xs font-bold border-2 border-cyan-500/25 transition-all cursor-pointer"
          >
            {copiedReport ? <Check className="w-4 h-4 text-emerald-400" /> : <Share2 className="w-4 h-4" />}
            <span>{copiedReport ? (language === 'hi' ? 'रिपोर्ट कॉपी हो गई' : 'Copied!') : (language === 'hi' ? 'रिपोर्ट कॉपी/शेयर करें' : 'Share Triage Report')}</span>
          </button>

          <button
            onClick={onReset}
            className="w-full sm:w-auto flex items-center justify-center gap-1.5 px-4 py-2.5 rounded-xl bg-red-600/20 hover:bg-red-600/30 active:translate-x-0.5 active:translate-y-0.5 text-red-300 border-2 border-red-500/50 text-xs font-bold transition-all cursor-pointer"
          >
            <RotateCcw className="w-4 h-4" />
            <span>{language === 'hi' ? 'नया ट्राइएज शुरू करें' : 'Start New Triage'}</span>
          </button>
        </div>
      </div>
    </div>
  );
};
